### ISSUE TITLE
Error in render_reactlog (argument "log" is missing)

### ISSUE THREAD

**Issue by jzadra** [rstudio/reactlog#12]
Following the usage example in the readme, I get an error that the log doesn't exist.  Also, the keys (command + F3) does not do anything while app is running.

> library(shiny)
> library(reactlog)
> 
> # tell shiny to log reactivity
> options("shiny.reactlog" = TRUE)
> 
> # run a shiny app
> app <- system.file("examples/01_hello", package = "shiny")
> runApp(app)

Listening on http://127.0.0.1:4508

> 
> # once app has closed, display reactlog
> show_reactlog()
Error in render_reactlog(log, time = as.logical(time), ...) : 
  argument "log" is missing, with no default
> show_reactlog()
Error in render_reactlog(log, time = as.logical(time), ...) : 
  argument "log" is missing, with no default

**Comment by condour** [comment]
Seeing the above as well.

**Comment by schloerke** [comment]
Fixed in #23 . Will be in the next release shortly.

Thank you for testing the package! Please let me know if you find any more bugs.
