### ISSUE TITLE
ctrl-F4 behavior

### ISSUE THREAD

**Issue by r2evans** [rstudio/reactlog#39]
FF (as well as other browsers on windows) binds `CTRL-F4` to "close tab", and there does not appear to be a way to configure it to do otherwise.

Their [list of shortcuts](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) suggests that it does not close ***pinned tabs***, but it appears to still intercept and ignore the key, so I believe `shiny` never sees the keypress.

Is it possible to override the key trigger? If not, I suggest the documentation be changed to clearly identify the browser that is required to support user-marks.

This seems to affect:

- FF 67.0.1 (64-bit)
- Edge 44.17763.1.0, EdgeHTML 18.17763
- Internet Explorer 11.503.17763.0, update version 11.0.125

I'm on win10, R-3.5.3, shiny-1.3.2, reactlog-1.0.0

(BTW: I also tried to send the keypress artificially, using a suggestion from https://stackoverflow.com/a/12187302, no luck.)

**Comment by schloerke** [comment]
😞 Correct. https://www.shortcuts-keyboard.com/chrome-shortcuts-keyboard/

Could you try within RStudio IDE?

This is currently hard coded within shiny.  Will need to update shiny to have this fixed.

**Comment by r2evans** [comment]
I was afraid of that ... it's inconvenient primarily for my muscle-memory, which really benefits from years in emacs/ess, and stumbles woefully and slowly anywhere else.

If this is not a realistic feature-request (adding configurability for non-RStudio browsers), then I suggest this issue be re-purposed into "state this requirement in the vignette/website/documentation". Otherwise, feel free to close this issue.

Thanks!

**Comment by r2evans** [comment]
Thanks for copying over to rstudio/shiny#2478

**Comment by schloerke** [comment]
Merged in `rstudio/shiny@master`. Closing.
