### ISSUE TITLE
Only a very simple interface is available (no navigation bars etc)

### ISSUE THREAD

**Issue by petr-fedorov** [rstudio/reactlog#40]
I'm on Fedora 29, RStudio 1.1.463 R 3.5.3

Tried all types of reactlog installation: CRAN, install_github and build. In all cases what I see after pressing Ctrl+F3 or running `shiny::showReactLog()`  is shown below:
![reactlog](https://user-images.githubusercontent.com/949629/59023429-78669880-8858-11e9-969d-6f184f4b2427.png)

i.e. I can only navigate with Home, End and  Left, Right arrows - nothing else!

**Comment by schloerke** [comment]
I don't believe you are running the latest `shiny`/`reactlog` R packages.

Please restart R and try again. 

If that does not fix it, please post your `sessioninfo::session_info()`

**Comment by hadley** [comment]
I think you should address this specifically on the readme — does your reactlog look like this? Then you need  `install.packages(c("shiny", "reactlog"))`

**Comment by petr-fedorov** [comment]
@schloerke @hadley I have updated to shiny 1.3.2 and it works now. Thanks !
