### ISSUE TITLE
Use of Github LFS breaks devtools::install_github()

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/reactlog#49]
I thought I had the same problem as #47 (I opened the reactlog in a shinydashboard and the reactive graph was missing) but upon further inspection in the browser console, I noticed a

```
SyntaxError: unexpected token: identifier
```

in `reactlog.js:1:8`. Inspecting the source of this file (`reactlogAsset/reactlog.js`) shows the file source as

```
version https://git-lfs.github.com/spec/v1
oid sha256:7b7a2271d7aa4350090323c4031843b60190e5f52557b545a960bc165e450e92
size 710689
```

This is just after installing reactlog using `devtools::install_github("rstudio/reactlog")` and I'm fairly confident that `devtools::install_github()` doesn't work with git LFS (see https://github.com/r-lib/devtools/issues/889 and https://github.com/r-lib/devtools/issues/1476), hence the missing `reactlog.js` file. Re-installing reactlog from CRAN resolved the issue completely.

Here's a small reprex that I ran in the latest [rocker/verse](https://hub.docker.com/r/rocker/verse) docker image to confirm.

``` r
devtools::install_github("rstudio/reactlog")
readLines(system.file("reactlog", "reactlogAsset", "reactlog.js", package = "reactlog"))[1:3]
#> [1] "version https://git-lfs.github.com/spec/v1"                                 
#> [2] "oid sha256:7b7a2271d7aa4350090323c4031843b60190e5f52557b545a960bc165e450e92"
#> [3] "size 710689"

install.packages("reactlog")
#> Installing package into '/usr/local/lib/R/site-library'
#> (as 'lib' is unspecified)
readLines(system.file("reactlog", "reactlogAsset", "reactlog.js", package = "reactlog"))[1]
#> Warning in readLines(system.file("reactlog", "reactlogAsset",
#> "reactlog.js", : incomplete final line found on '/usr/local/lib/R/site-
#> library/reactlog/reactlog/reactlogAsset/reactlog.js'
#> [1] "!function(e){var t={};function n(r){if(t[r])return t[r]...
```

**Comment by schloerke** [comment]
😢 

Thank you for the issue! I'll see if I can get that later today.
