### ISSUE TITLE
File observer shows up with new version of shiny

### ISSUE THREAD

**Issue by akgold** [rstudio/reactlog#58]
When using reactlog with the newest version of shiny (1.4.0.9001), I'm getting a weird extra reactive showing up in my app, that I *think* is the observer watching the `R/` folder. I found this confusing when I first saw it. Maybe there's a way to exclude it? Or make clear what it is?

Here's an example using the geyser app.
<img width="1443" alt="Screen Shot 2019-12-02 at 09 35 12" src="https://user-images.githubusercontent.com/394930/69967792-22ad3900-14e7-11ea-8fca-4f56967c6f4b.png">

**Comment by schloerke** [comment]
Can you make a PR to shiny at https://github.com/rstudio/shiny/blob/1080cf0ef4c5b6576fcdfebad1c555dcba97ce3a/R/app.R#L287 and add `label` with something appropriate? `Shiny Auto-reload`?

Thank you @akgold

**Comment by schloerke** [comment]
Thank you for the picture!!
