### ISSUE TITLE
Refresh icon is out of date

### ISSUE THREAD

**Issue by schloerke** [rstudio/reactlog#77]
> The `name` provided ('refresh') is deprecated in Font Awesome 5:
> * please consider using 'sync' or 'fas fa-sync' instead
> * use the `verify_fa = FALSE` to deactivate these messages

Due to shiny + FontAwesome5 updates

**Comment by Steviey** [comment]
Where to say verify_fa?

**Comment by schloerke** [comment]
Instead of `verify_fa = FALSE`...

Let's update the icon name to `sync` here: https://github.com/rstudio/reactlog/blob/31c519d936e413a10f73ed4124bac8fa800e0416/R/shinyModule.R#L65

and require `>=` shiny version 1.7.0 because of this commit https://github.com/rstudio/shiny/commit/d65ad5ea90a3ab7bbc75bb597272a2da80beb7c5

**Comment by willtudorevans** [comment]
Hello, curious if this fix been applied? I'm still getting warning messages with latest version of Shiny (v1.72), R (v4.2.1) and reactlog (v1.1.0).

**Comment by schloerke** [comment]
`{reactlog}` v1.1.1 is being processed by CRAN. 🎊
